version: "3.8"

services:
  web:
    image: baklachok/stripe:latest
    container_name: stripe_django
    restart: always
    env_file: .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate &&
            python /app/scripts/create_superuser.py &&
            python manage.py collectstatic --noinput &&
            gunicorn --bind 0.0.0.0:8000 stripe_project.wsgi:application"
    volumes:
      - ./staticfiles:/app/staticfiles

  db:
    image: postgres:15
    container_name: stripe_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
